apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graphql-server
  namespace: prisma
  labels:
    stage: production
    name: graphql-server
    app: social-network-template
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: production
        name: graphql-server
        app: social-network-template
    spec:
      containers:
      - name: graphql-server
        image: davidchristie/graphql-server:v3
        imagePullPolicy: Always
        env:
        - name: JWT_SECRET
          value: 'jwt_secret123'
        - name: PRISMA_ENDPOINT
          value: 'http://prisma.prisma:4466/social-network-template/production'
