projects:
  data-model:
    schemaPath: packages/public-api/src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: ../public-api/src/generated/prisma.ts
  public-api:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
