projects:
  data-model:
    schemaPath: packages/data-model/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: ../data-model/generated/prisma.ts
  public-api:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
