version: '3'
services:
  social-network:
    build:
      context: .
      dockerfile: 'production.Dockerfile'
  authentication:
    build:
      dockerfile: 'packages/authentication/production.Dockerfile'
  public-api:
    build:
      dockerfile: 'packages/public-api/production.Dockerfile'
  web-client:
    build:
      dockerfile: 'packages/web-client/production.Dockerfile'
      args:
        - 'REACT_APP_API_ENDPOINT=http://public-api:4000'
