version: '3'

services:
  graphql-server:
    image: davidchristie/graphql-server
    build:
      context: .
      dockerfile: 'packages/graphql-server/Dockerfile'
    ports:
      - '4000:4000'
    volumes:
      - '/app/node_modules'
      - '/app/packages/data-model/node_modules'
      - '/app/packages/graphql-server/node_modules'
