version: '3'

services:
  public-api:
    image: davidchristie/public-api:v1
    build:
      context: .
      dockerfile: 'packages/public-api/Dockerfile'
    ports:
      - '4000:4000'
    volumes:
      - '/app/node_modules'
