version: '3'

services:
  authentication:
    build:
      dockerfile: 'packages/authentication/production.Dockerfile'

  public-api:
    build:
      dockerfile: 'packages/public-api/production.Dockerfile'

  web-client:
    build:
      dockerfile: 'packages/web-client/production.Dockerfile'
      args:
        - 'API_ENDPOINT=http://public-api:4000'
