version: '3'

services:
  authentication:
    build:
      dockerfile: 'packages/authentication/development.Dockerfile'
    volumes: &volumes
      - '.:/app'

  build-packages:
    volumes: *volumes

  data-model:
    build:
      context: .
      dockerfile: 'packages/data-model/Dockerfile'
    environment:
      - 'PRISMA_ENDPOINT=http://prisma:4466/social-network/production'
    depends_on:
      - build-packages
      - prisma

  public-api:
    build:
      dockerfile: 'packages/public-api/development.Dockerfile'
    volumes: *volumes

  web-client:
    build:
      dockerfile: 'packages/web-client/development.Dockerfile'
    environment:
      - 'REACT_APP_API_ENDPOINT=http://localhost:4000'
    volumes: *volumes
