version: "3.7"

services:
  authentication:
    build:
      context: .
      dockerfile: packages/backend/authentication/Dockerfile

  public-api:
    build:
      context: .
      dockerfile: packages/backend/public-api/Dockerfile

  web-client:
    build:
      context: .
      dockerfile: packages/frontend/web-client/Dockerfile
      args:
        - API_ENDPOINT=https://api.social-network.davidchristie.io
