version: '3'
services:
  end-to-end:
    build:
      context: .
      dockerfile: 'packages/end-to-end/Dockerfile'
    environment:
      - 'ORIGIN=http://web-client:3000'
networks:
  default:
    external:
      name: default
