version: "3.7"

x-defaults: &defaults
  image: node:10-alpine
  volumes:
    - .:/app/
  entrypoint: ["yarn", "start"]

services:
  authentication:
    <<: *defaults
    working_dir: /app/packages/backend/authentication/

  public-api:
    <<: *defaults
    working_dir: /app/packages/backend/public-api/

  web-client:
    <<: *defaults
    working_dir: /app/packages/frontend/web-client/
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:4000
