version: '3'

services:
  authentication:
    build:
      dockerfile: 'packages/backend/authentication/development.Dockerfile'
    volumes: &volumes
      - '.:/app'

  public-api:
    build:
      dockerfile: 'packages/backend/public-api/development.Dockerfile'
    volumes: *volumes

  web-client:
    build:
      dockerfile: 'packages/frontend/web-client/development.Dockerfile'
    environment:
      - 'REACT_APP_API_ENDPOINT=http://localhost:4000'
    volumes: *volumes
