version: '3'

services:
  authentication:
    image: davidchristie/authentication:${VERSION}
    build:
      context: .
    ports:
      - '5000:5000'
    environment:
      - 'JWT_SECRET=jwt_secret123'
      - 'PRISMA_ENDPOINT=http://prisma:4466/social-network/production'
    depends_on:
      - prisma

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql

  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - "4467:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
    depends_on:
      - mysql

  public-api:
    image: davidchristie/public-api:${VERSION}
    build:
      context: .
    ports:
      - '4000:4000'
    environment:
      - 'AUTHENTICATION_ENDPOINT=http://authentication:5000'
      - 'PRISMA_ENDPOINT=http://prisma:4466/social-network/production'
    depends_on:
      - authentication
      - prisma

  web-client:
    image: davidchristie/web-client:${VERSION}
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - public-api

volumes:
  mysql:
