version: "3.7"

services:
  authentication:
    image: davidchristie/authentication:${VERSION:-latest}
    ports:
      - 5000:5000
    environment:
      - JWT_SECRET=jwt_secret123
      - PRISMA_ENDPOINT=http://prisma:4466/social-network/production
    depends_on:
      - prisma

  kafka:
    image: spotify/kafka
    ports:
    - "2181:2181"
    - "9092:9092"
    environment:
    - "ADVERTISED_HOST=kafka"
    - "ADVERTISED_PORT=9092"
    - "AUTO_CREATE_TOPICS=true"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql

  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
    - "4467:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
    depends_on:
      - mysql

  public-api:
    image: davidchristie/public-api:${VERSION:-latest}
    ports:
      - 4000:4000
    environment:
      - AUTHENTICATION_ENDPOINT=http://authentication:5000
      - PRISMA_ENDPOINT=http://prisma:4466/social-network/production
    depends_on:
      - authentication
      - prisma

  web-client:
    image: davidchristie/web-client:${VERSION:-latest}
    ports:
      - 3000:3000
    depends_on:
      - public-api

volumes:
  mysql:
