version: '3'
services:
  social-network:
    image: davidchristie/social-network:v1
    build:
      context: .
  authentication:
    image: davidchristie/authentication:v2
    build:
      context: .
      dockerfile: 'packages/authentication/production.Dockerfile'
    ports:
      - '5000:5000'
    environment:
      - 'JWT_SECRET=jwt_secret123'
      - 'PRISMA_ENDPOINT=http://prisma:4466/social-network/production'
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - "4467:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  public-api:
    image: davidchristie/public-api:v3
    build:
      context: .
      dockerfile: 'packages/public-api/production.Dockerfile'
    ports:
      - '4000:4000'
    environment:
      - 'AUTHENTICATION_ENDPOINT=http://authentication:5000'
      - 'PRISMA_ENDPOINT=http://prisma:4466/social-network/production'
volumes:
  mysql:
