version: '3'

services:
  graphql-server:
    image: davidchristie/graphql-server:v3
    build:
      context: .
      dockerfile: 'packages/graphql-server/Dockerfile'
    ports:
      - '4000:4000'
    volumes:
      - '/app/node_modules'
