apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: public-api
  namespace: social-network
  labels:
    stage: production
    name: public-api
    app: social-network-template
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        stage: production
        name: public-api
        app: social-network-template
    spec:
      containers:
      - name: public-api
        image: davidchristie/public-api:v4
        env:
        - name: AUTHENTICATION_ENDPOINT
          value: 'http://authentication.social-network:5000'
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: authentication
              key: jwt-secret
        - name: PRISMA_ENDPOINT
          value: 'http://prisma.social-network:4466/social-network/production'
