apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: public-api
  namespace: social-network
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "public-api"
spec:
  tls:
    - secretName: public-api-tls
  backend:
    serviceName: public-api
    servicePort: 4000
