apiVersion: v1
kind: Service
metadata:
  name: public-api
  namespace: social-network
  labels:
    stage: production
    name: public-api
    app: social-network-template
spec:
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    app: social-network-template
    name: public-api
    stage: production
