version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies.
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # Fallback to using the latest cache if no exact match is found.
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run unit tests
          command: yarn test:unit
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Start microservices
          command: |
              yarn production build --no-cache
              yarn production up --detach
      - run:
          name: List production images
          command: yarn production images
      - run:
          name: Deploy Prisma data-model
          command: |
              docker build \
                  --file packages/data-model/Dockerfile \
                  --tag davidchristie/data-model .
              docker run \
                  --network repo_default \
                  --env "PRISMA_ENDPOINT=http://prisma:4466/social-network/production" \
                  davidchristie/data-model
      - run:
          name: Run end-to-end tests
          command: |
              docker build \
                  --file packages/end-to-end/Dockerfile \
                  --tag  davidchristie/end-to-end .
              docker run \
                  --env "ORIGIN=http://web-client:3000" \
                  --network repo_default davidchristie/end-to-end
