version: 2

references:

  # Steps

  link-dependencies: &link-dependencies
    run:
      name: Link dependencies
      command: yarn install --offline

  restore-cache: &restore-cache
    restore_cache:
      keys:
        # When lock file changes, use increasingly general patterns to
        # restore cache.
        - v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - v1-{{ .Branch }}-
        - v1-

  # Jobs

  defaults: &defaults
    docker:
    - image: circleci/node:9.11
    working_directory: ~/repo

  build-package: &build-package
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - *restore-cache
      - *link-dependencies
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Build production image
          command: |
              yarn production build $PACKAGE

  test-package: &test-package
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - *restore-cache
      - *link-dependencies
      - run:
          name: Run unit tests
          command: yarn $PACKAGE test
      - run:
          name: Format coverage report
          command: |
              ./tmp/test-reporter format-coverage -t lcov \
                  -o tmp/coverage.$PACKAGE.json \
                  packages/$PACKAGE/coverage/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - coverage.*.json

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore-cache
      - *link-dependencies
      - run:
          name: Build packages
          command: yarn build
      - setup_remote_docker
      - run:
          name: Start microservices
          command: |
              yarn production build
              yarn production up --detach
      - run:
          name: List production images
          command: yarn production images
      - run:
          name: List production containers
          command: yarn production ps
      - run:
          name: Deploy Prisma data-model
          command: |
              docker build \
                  --file packages/data-model/Dockerfile \
                  --tag davidchristie/data-model .
              docker run \
                  --network repo_default \
                  --env "PRISMA_ENDPOINT=http://prisma:4466/social-network/production" \
                  davidchristie/data-model
      - run:
          name: Run end-to-end tests
          command: |
              docker build \
                  --file docker/end-to-end-tests.Dockerfile \
                  --tag end-to-end-tests .
              docker run \
                  --env "ORIGIN=http://web-client:3000" \
                  --network repo_default end-to-end-tests

  build-authentication:
    <<: *defaults
    <<: *build-package
    environment:
      PACKAGE: authentication

  build-public-api:
    <<: *defaults
    <<: *build-package
    environment:
      PACKAGE: public-api

  build-web-client:
    <<: *defaults
    <<: *build-package
    environment:
      PACKAGE: web-client

  download-test-reporter:
    <<: *defaults
    steps:
      - run:
          name:  Download test reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/test-reporter
            chmod +x ./tmp/test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - test-reporter

  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - *restore-cache
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

  puppeteer-image:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Check for changes
          command: |
              if [ -z $(git diff --name-only HEAD~ docker/puppeteer.Dockerfile) ]
              then
                echo "No changes in the last commit"
                circleci step halt
              else
                echo "Was changed in the last commit"
              fi
      - setup_remote_docker
      - run:
          name: Log in to docker
          command: |
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Set image name
          command: |
              echo 'IMAGE="$DOCKER_USERNAME/puppeteer"' >> $BASH_ENV
              echo 'VERSION="$(git rev-parse --short HEAD)"' >> $BASH_ENV
      - run:
          name: Build image
          command: |
              docker build \
                  --file docker/puppeteer.Dockerfile \
                  --tag $IMAGE:latest \
                  --tag $IMAGE:$VERSION \
                  .
      - run:
          name: Push image
          command: |
              docker push $IMAGE

  test-authentication:
    <<: *defaults
    <<: *test-package
    environment:
      PACKAGE: authentication

  test-public-api:
    <<: *defaults
    <<: *test-package
    environment:
      PACKAGE: public-api

  test-web-client:
    <<: *defaults
    <<: *test-package
    environment:
      PACKAGE: web-client

  upload-coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/test-reporter sum-coverage tmp/coverage.*.json \
                --parts 3 \
                --output tmp/coverage.total.json
            ./tmp/test-reporter upload-coverage \
              --id $CODE_CLIMATE_TEST_REPORTER_ID \
              --input tmp/coverage.total.json

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          requires:
            - build-authentication
            - build-public-api
            - build-web-client
      - build-authentication:
          requires:
            - upload-coverage
      - build-public-api:
          requires:
            - upload-coverage
      - build-web-client:
          requires:
            - upload-coverage
      - download-test-reporter:
          requires:
            - puppeteer-image
      - install-dependencies:
          requires:
            - puppeteer-image
      - puppeteer-image
      - test-authentication:
          requires:
            - download-test-reporter
            - install-dependencies
      - test-public-api:
          requires:
            - download-test-reporter
            - install-dependencies
      - test-web-client:
          requires:
            - download-test-reporter
            - install-dependencies
      - upload-coverage:
          requires:
            - test-authentication
            - test-public-api
            - test-web-client
