version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies.
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # Fallback to using the latest cache if no exact match is found.
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:unit
      - setup_remote_docker:
          docker_layer_caching: true
      - run: yarn production
      - run: docker-compose ps
      - run: docker network ls
      - run:
          name: Deploy Prisma data-model
          command: |
              docker build \
                  --file packages/data-model/Dockerfile \
                  --tag davidchristie/data-model .
              docker run \
                  --network social-network-template_default \
                  --env "PRISMA_ENDPOINT=http://prisma:4466/social-network/production" \
                  davidchristie/data-model
      - run: docker build --file packages/end-to-end/Dockerfile --tag  davidchristie/end-to-end .
      - run: docker run --network repo_default davidchristie/end-to-end curl http://web-client:3000
      - run: docker run --env "ORIGIN=http://web-client:3000" --network repo_default davidchristie/end-to-end
