kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-disk
  namespace: social-network
  labels:
    stage: production
    name: database
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
