apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: social-network
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    stage: production
    name: database
    app: mysql
