apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication
  namespace: social-network
  labels:
    stage: production
    name: authentication
    app: social-network
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        stage: production
        name: authentication
        app: social-network
    spec:
      containers:
      - name: authentication
        image: davidchristie/authentication:d5ca0b0
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: authentication
              key: jwt-secret
        - name: PRISMA_ENDPOINT
          value: 'http://prisma.social-network:4466/social-network/production'
