apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: public-api
  namespace: prisma
  labels:
    stage: production
    name: public-api
    app: social-network-template
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        stage: production
        name: public-api
        app: social-network-template
    spec:
      containers:
      - name: public-api
        image: davidchristie/public-api:v2
        env:
        - name: JWT_SECRET
          value: 'jwt_secret123'
        - name: PRISMA_ENDPOINT
          value: 'http://prisma.prisma:4466/social-network-template/production'
